services:
  graphql-backend-api:
    container_name: graphql-backend
    build: ./
    command: pnpm serve
    environment:
      - MONGODB_URL=mongodb://user:pass@mongo:27017/graphql
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      - ./:/server
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: graphql

